spring:
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL5InnoDBDialect'
# h2 웹 콘솔 활성화
  h2:
    console:
      enabled: true
  profiles:
    include: 'oauth'
# 세션 저장소 설정
  session:
    store-type: jdbc


